package net.streamroutes.sreamroutesapp.Navigation

sealed class AppScreens (val route: String) {
    object SplashScreen: AppScreens("splash_screen")
    object LoginScreen: AppScreens("login_screen")
    object RegistrationScreen: AppScreens("registration_screen")
    object VerificationScreen: AppScreens("verification_screen")
    object ChangeScreen: AppScreens("change_screen")
    object MainScreen: AppScreens("main_screen")
    object ProfileScreen: AppScreens("profile_screen")
    object ProfileConfigurationScreen: AppScreens("profile_configure_screen")
    object ProfilePersonalInfoScreen: AppScreens("profile_data_info_screen")
    object ProfileChangePhoneScreen: AppScreens("profile_change_phone_screen")
    object ProfileChangeEmailScreen: AppScreens("profile_change_email_screen")
    object HelpScreen: AppScreens("help_screen")
    object HelpCommentsScreen: AppScreens("help_comments_screen")
    object HelpContactScreen: AppScreens("help_contact_screen")
    object HelpAboutAppScreen: AppScreens("help_about_screen")
    object RoutesScreen: AppScreens("routes_screen")
    object MenuScreen: AppScreens("menu_screen")
    object ConfigurationScreen: AppScreens("configuracion_screen")
    object MapOptionsScreen: AppScreens("mapa_options_screen")
    object ChangeCityScreen: AppScreens("change_city_screen")
    object NotificationsScreen: AppScreens("notifications_screen")
    object PrivacityScreen: AppScreens("privacity_screen")
    object TripScreen: AppScreens("trip_screen")
    object SuscripcionScreen: AppScreens("premium_screen")
    object ValoranoScreen: AppScreens("valoranos_screen")
    object LanguageScreen: AppScreens("language_screen")
    object ResenaScreen: AppScreens("resena_screen")
    object SuscriptionConfigurationScreen: AppScreens("suscripction_configuration_screen")
    object StreamRoutesMapScreen: AppScreens("stream_routes_map_screen")
}

